import pandas as pd
import numpy as np
import argparse
import os
import tempfile
from typing import List, Tuple, Dict, Union


FrameKey = Union[int, Tuple[int, int]]
TARGET_PERSON_ID = 1
DEFAULT_GRAPH_FPS = 30.0
DEFAULT_GRAPH_WINDOW_SECONDS = 30.0
GRAPH_VIDEO_GROUPS = {
    "left_upper_body": [
        "left_shoulder_angle",
        "left_elbow_angle",
    ],
    "right_upper_body": [
        "right_shoulder_angle",
        "right_elbow_angle",
    ],
    "middle": [
        "trunk_flexion",
        "trunk_lateral_flexion",
        "neck_flexion",
        "neck_lateral_flexion",
    ],
}

def project_to_frontal(point: np.ndarray) -> np.ndarray:
    """ 
    Project a MediaPipe 3D landmark onto the camera's frontal image plane.

    MediaPipe pose uses x/y image coordinates and z depth. For this project,
    frontal-plane angles are calculated from x/y only, so depth is discarded.
    """
    point = np.array(point)
    return np.array([point[0], point[1], 0.0])


def safe_vector_angle(vector_a: np.ndarray, vector_b: np.ndarray) -> float:
    """
    Calculate the angle between two already projected vectors.
    Returns NaN if either vector has zero length.
    """
    vector_a = np.array(vector_a)
    vector_b = np.array(vector_b)

    denominator = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
    if denominator == 0 or np.isnan(denominator):
        return np.nan

    cosine_angle = np.dot(vector_a, vector_b) / denominator
    return np.degrees(np.arccos(np.clip(cosine_angle, -1.0, 1.0)))

def calculate_angle(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> float:
    """
    Calculate the frontal-plane angle between three MediaPipe points.
    The angle is calculated at point b.
    """
    # Convert to numpy arrays if not already
    a = project_to_frontal(a)
    b = project_to_frontal(b)
    c = project_to_frontal(c)
    
    # Calculate vectors
    ba = a - b
    bc = c - b
    
    return safe_vector_angle(ba, bc)


def parse_pose_csv(csv_file: str) -> pd.DataFrame:
    """
    Parse the CSV file generated by the pose estimation script.
    Returns a DataFrame with all landmark coordinates.
    """
    # Read the CSV file
    df = pd.DataFrame()
    try:
        df = pd.read_csv(csv_file)
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return None

    if "person_id" in df.columns:
        original_rows = len(df)
        person_ids = pd.to_numeric(df["person_id"], errors="coerce")
        df = df[person_ids == TARGET_PERSON_ID].copy()
        print(
            f"Imported {len(df)} rows for person ID {TARGET_PERSON_ID} "
            f"from {original_rows} total rows."
        )
    
    return df


def extract_landmark_coordinates(df: pd.DataFrame) -> Dict[FrameKey, List[Tuple[float, float, float]]]:
    """
    Extract coordinates for each landmark from all frames.
    Returns a dictionary mapping frame_index or (frame, person_id) -> list of landmark coordinates.
    """
    frames_data = {}
    
    for frame_idx, row in df.iterrows():
        landmarks = []
        
        # For each of the 33 landmarks
        for i in range(33):
            x = row[f"landmark_{i}_x"]
            y = row[f"landmark_{i}_y"]
            z = row[f"landmark_{i}_z"]
            landmarks.append((x, y, z))
        
        if "frame" in df.columns and "person_id" in df.columns:
            key = (int(row["frame"]), int(row["person_id"]))
        else:
            key = frame_idx

        frames_data[key] = landmarks
    
    return frames_data


def calculate_kinematics(frames_data: Dict[FrameKey, List[Tuple[float, float, float]]]) -> pd.DataFrame:
    """
    Calculate clinically relevant kinematics from the landmark data.
    Returns a DataFrame with all calculated kinematics.
    """
    # Define the landmark indices for various joints
    # MediaPipe pose landmarks reference: https://mediapipe.dev/images/mobile/pose_tracking_full_body_landmarks.png
    landmarks = {
        # Left side
        "left_shoulder": 11,
        "left_elbow": 13,
        "left_wrist": 15,
        "left_hip": 23,
        "left_knee": 25,
        "left_ankle": 27,
        # Right side
        "right_shoulder": 12,
        "right_elbow": 14,
        "right_wrist": 16,
        "right_hip": 24,
        "right_knee": 26,
        "right_ankle": 28,
        # Central points
        "nose": 0,
        "neck": 33,  # Not directly in MediaPipe, we'll calculate it
        "left_ear": 7,
        "right_ear": 8,
    }
    
    # Initialize a dictionary to store the kinematics data
    kinematics_data = {
        # Joint angles
        "left_knee_angle": [],
        "right_knee_angle": [],
        "left_hip_angle": [],
        "right_hip_angle": [],
        "left_ankle_angle": [],
        "right_ankle_angle": [],
        "left_shoulder_angle": [],
        "right_shoulder_angle": [],
        "left_elbow_angle": [],
        "right_elbow_angle": [],
        # Trunk angles
        "trunk_flexion": [],
        "trunk_lateral_flexion": [],
        # Neck angles
        "neck_flexion": [],
        "neck_lateral_flexion": [],
        # Symmetry metrics
        "knee_angle_symmetry": [],
        "hip_angle_symmetry": [],
        "shoulder_angle_symmetry": []
    }
    
    # Process each frame
    for frame_idx, landmarks_list in frames_data.items():
        # Create a function to get coordinates for a landmark
        def get_landmark(idx):
            if idx == 33:  # Calculate neck position as midpoint between shoulders
                left_shoulder = np.array(landmarks_list[landmarks["left_shoulder"]])
                right_shoulder = np.array(landmarks_list[landmarks["right_shoulder"]])
                return (left_shoulder + right_shoulder) / 2
            else:
                return np.array(landmarks_list[idx])
        
        # Calculate joint angles
        
        # Knee angles in the frontal image plane
        left_knee_angle = calculate_angle(
            get_landmark(landmarks["left_hip"]), 
            get_landmark(landmarks["left_knee"]), 
            get_landmark(landmarks["left_ankle"])
        )
        right_knee_angle = calculate_angle(
            get_landmark(landmarks["right_hip"]), 
            get_landmark(landmarks["right_knee"]), 
            get_landmark(landmarks["right_ankle"])
        )
        
        # Hip angles in the frontal image plane
        # Use image vertical as reference from the hip
        left_hip_vertical = get_landmark(landmarks["left_hip"]) + np.array([0, -1, 0])
        right_hip_vertical = get_landmark(landmarks["right_hip"]) + np.array([0, -1, 0])
        
        left_hip_angle = calculate_angle(
            left_hip_vertical, 
            get_landmark(landmarks["left_hip"]), 
            get_landmark(landmarks["left_knee"])
        )
        right_hip_angle = calculate_angle(
            right_hip_vertical, 
            get_landmark(landmarks["right_hip"]), 
            get_landmark(landmarks["right_knee"])
        )
        
        # Ankle angles in the frontal image plane
        # Use image horizontal as reference from the ankle
        left_ankle_horizontal = get_landmark(landmarks["left_ankle"]) + np.array([1, 0, 0])
        right_ankle_horizontal = get_landmark(landmarks["right_ankle"]) + np.array([1, 0, 0])
        
        left_ankle_angle = calculate_angle(
            get_landmark(landmarks["left_knee"]),
            get_landmark(landmarks["left_ankle"]),
            left_ankle_horizontal
        )
        right_ankle_angle = calculate_angle(
            get_landmark(landmarks["right_knee"]),
            get_landmark(landmarks["right_ankle"]),
            right_ankle_horizontal
        )
        
        # Shoulder angles in the frontal image plane
        # left_shoulder_vertical = get_landmark(landmarks["left_shoulder"]) + np.array([0, -1, 0])
        # right_shoulder_vertical = get_landmark(landmarks["right_shoulder"]) + np.array([0, -1, 0])
        
        left_shoulder_angle = calculate_angle(
            get_landmark(landmarks["left_hip"]),
            get_landmark(landmarks["left_shoulder"]),
            get_landmark(landmarks["left_elbow"])
        )
        right_shoulder_angle = calculate_angle(
            get_landmark(landmarks["right_hip"]),
            get_landmark(landmarks["right_shoulder"]),
            get_landmark(landmarks["right_elbow"])
        )
        
        # Elbow angles in the frontal image plane
        left_elbow_angle = calculate_angle(
            get_landmark(landmarks["left_shoulder"]),
            get_landmark(landmarks["left_elbow"]),
            get_landmark(landmarks["left_wrist"])
        )
        right_elbow_angle = calculate_angle(
            get_landmark(landmarks["right_shoulder"]),
            get_landmark(landmarks["right_elbow"]),
            get_landmark(landmarks["right_wrist"])
        )
        
        # Trunk angle relative to image vertical in the frontal plane
        left_hip = get_landmark(landmarks["left_hip"])
        right_hip = get_landmark(landmarks["right_hip"])
        hip_center = (left_hip + right_hip) / 2
        
        left_shoulder = get_landmark(landmarks["left_shoulder"])
        right_shoulder = get_landmark(landmarks["right_shoulder"])
        shoulder_center = (left_shoulder + right_shoulder) / 2
        
        # Create a vertical line from hip center
        hip_vertical = hip_center + np.array([0, -1, 0])
        
        trunk_flexion = calculate_angle(
            hip_vertical,
            hip_center,
            shoulder_center
        )
        
        # Trunk lateral angle in the frontal image plane
        # Create a line from left hip to right hip
        left_hip_frontal = project_to_frontal(left_hip)
        right_hip_frontal = project_to_frontal(right_hip)
        hip_line = right_hip_frontal - left_hip_frontal
        # Create a perpendicular line (up) from the hip line
        hip_up = np.cross(hip_line, np.array([0, 0, 1]))
        hip_up_norm = np.linalg.norm(hip_up)
        if hip_up_norm == 0 or np.isnan(hip_up_norm):
            hip_up = np.array([0, -1, 0])
        else:
            hip_up = hip_up / hip_up_norm
        
        # Line from hip center to shoulder center
        hip_to_shoulder = shoulder_center - hip_center
        
        # Project hip_to_shoulder onto the frontal plane
        frontal_plane_normal = np.array([0, 0, 1])
        hip_to_shoulder_frontal = hip_to_shoulder - np.dot(hip_to_shoulder, frontal_plane_normal) * frontal_plane_normal
        
        # Calculate the angle between hip_up and hip_to_shoulder_frontal
        trunk_lateral_flexion = safe_vector_angle(hip_up, hip_to_shoulder_frontal)
        
        # Neck angles
        neck = get_landmark(landmarks["neck"])
        nose = get_landmark(landmarks["nose"])
        
        # Neck angle relative to image vertical in the frontal plane
        neck_vertical = neck + np.array([0, -1, 0])
        neck_flexion = calculate_angle(
            neck_vertical,
            neck,
            nose
        )
        
        # Neck lateral angle in the frontal image plane
        left_ear = get_landmark(landmarks["left_ear"])
        right_ear = get_landmark(landmarks["right_ear"])
        ear_center = (left_ear + right_ear) / 2
        
        # Create a vector from neck to ear center
        neck_to_ear = ear_center - neck
        
        # Project neck_to_ear onto the frontal plane
        neck_to_ear_frontal = neck_to_ear - np.dot(neck_to_ear, frontal_plane_normal) * frontal_plane_normal
        
        # Calculate the angle between vertical and neck_to_ear_frontal
        neck_lateral_flexion = safe_vector_angle(np.array([0, -1, 0]), neck_to_ear_frontal)
        
        # Calculate symmetry metrics (absolute difference between left and right)
        knee_angle_symmetry = abs(left_knee_angle - right_knee_angle)
        hip_angle_symmetry = abs(left_hip_angle - right_hip_angle)
        shoulder_angle_symmetry = abs(left_shoulder_angle - right_shoulder_angle)
        
        # Store the calculated kinematics
        kinematics_data["left_knee_angle"].append(left_knee_angle)
        kinematics_data["right_knee_angle"].append(right_knee_angle)
        kinematics_data["left_hip_angle"].append(left_hip_angle)
        kinematics_data["right_hip_angle"].append(right_hip_angle)
        kinematics_data["left_ankle_angle"].append(left_ankle_angle)
        kinematics_data["right_ankle_angle"].append(right_ankle_angle)
        kinematics_data["left_shoulder_angle"].append(left_shoulder_angle)
        kinematics_data["right_shoulder_angle"].append(right_shoulder_angle)
        kinematics_data["left_elbow_angle"].append(left_elbow_angle)
        kinematics_data["right_elbow_angle"].append(right_elbow_angle)
        kinematics_data["trunk_flexion"].append(trunk_flexion)
        kinematics_data["trunk_lateral_flexion"].append(trunk_lateral_flexion)
        kinematics_data["neck_flexion"].append(neck_flexion)
        kinematics_data["neck_lateral_flexion"].append(neck_lateral_flexion)
        kinematics_data["knee_angle_symmetry"].append(knee_angle_symmetry)
        kinematics_data["hip_angle_symmetry"].append(hip_angle_symmetry)
        kinematics_data["shoulder_angle_symmetry"].append(shoulder_angle_symmetry)
    
    # Create a DataFrame from the kinematics data
    kinematics_df = pd.DataFrame(kinematics_data)
    
    keys = list(frames_data.keys())
    if keys and isinstance(keys[0], tuple):
        kinematics_df.insert(0, "person_id", [key[1] for key in keys])
        kinematics_df.insert(0, "frame", [key[0] for key in keys])
    else:
        kinematics_df.insert(0, "frame", keys)
    
    return kinematics_df

def create_angle_graph_video(kinematics_df: pd.DataFrame,
    output_video: str,
    angle_columns: List[str],
    fps: float,
    title: str = "Joint Angles Over Time",
    window_seconds: float = DEFAULT_GRAPH_WINDOW_SECONDS,):
    """
    Create a video with graphs of the calculated angles over time.
    """
    import matplotlib.pyplot as plt
    import cv2

    df = kinematics_df.copy()
    df["time"] = df["frame"] / fps
    
    width, height = 960, 720

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    os.makedirs(os.path.dirname(output_video) or ".", exist_ok=True)
    writer = cv2.VideoWriter(output_video, fourcc, fps, (width, height))
    if not writer.isOpened():
        print(f"Error: Could not open video writer for {output_video}")
        return
    valid_angle_columns = [col for col in angle_columns if col in df.columns]
    if not valid_angle_columns:
        print("Error: No valid angle columns found in DataFrame")
        writer.release()
        return
    if df.empty:
        print(f"Error: No kinematics rows available for {output_video}")
        writer.release()
        return
    try:
        x_values = df["time"].to_numpy()
        total_frames = len(df)
        print(f"{title}: Starting video render to {output_video} ({total_frames} frames)")
        last_pct = -1
        for i in range(total_frames):
            current_time = x_values[i]
            x_max = max(window_seconds, current_time)
            x_min = max(0, x_max - window_seconds)

            plt.figure(figsize=(width / 100, height / 100), dpi=100)
            for col in valid_angle_columns:
                plt.plot(x_values[:i+1], df[col][:i+1], label=col)
            plt.xlabel("Time (s)")
            plt.ylabel("Angle (degrees)")
            plt.title(title)
            plt.legend()
            plt.xlim(x_min, x_max)
            plt.ylim(0, 180)
            plt.grid()

            plt.tight_layout()

            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as temp_file:
                temp_image = temp_file.name
            try:
                plt.savefig(temp_image)
                plt.close()

                frame = cv2.imread(temp_image)
                if frame is not None:
                    writer.write(frame)
                else:
                    print(f"Error: Could not read temporary image {temp_image}")
            finally:
                if os.path.exists(temp_image):
                    os.remove(temp_image)

            # Print progress as percentage, update only when it changes to reduce churn
            pct = int((i + 1) * 100 / max(1, total_frames))
            if pct != last_pct:
                print(f"{title}: Rendering frame {i+1}/{total_frames} ({pct}%)", end="\r", flush=True)
                last_pct = pct
    finally:
        writer.release()
        # Finish the progress line and print a newline
        print()
        print(f"{title} video saved to {output_video}")


def graph_video_paths(base_video: str) -> Dict[str, str]:
    """
    Build the three graph-video output paths from a single user-provided base path.
    """
    directory = os.path.dirname(base_video)
    stem, extension = os.path.splitext(os.path.basename(base_video))
    extension = extension or ".mp4"

    for suffix in ("_upper_body_angles", "_angles"):
        if stem.endswith(suffix):
            stem = stem[:-len(suffix)]
            break

    return {
        "left_upper_body": os.path.join(directory, f"{stem}_left_upper_body_angles{extension}"),
        "right_upper_body": os.path.join(directory, f"{stem}_right_upper_body_angles{extension}"),
        "middle": os.path.join(directory, f"{stem}_middle_angles{extension}"),
    }


def create_grouped_graph_videos(
    kinematics_df: pd.DataFrame,
    base_video: str,
    fps: float,
    window_seconds: float = DEFAULT_GRAPH_WINDOW_SECONDS,
) -> Dict[str, str]:
    """
    Create the left upper body, right upper body, and middle area graph videos.
    """
    output_paths = graph_video_paths(base_video)
    titles = {
        "left_upper_body": "Left Upper Body Angles Over Time",
        "right_upper_body": "Right Upper Body Angles Over Time",
        "middle": "Middle Area Angles Over Time",
    }

    for group_name, columns in GRAPH_VIDEO_GROUPS.items():
        create_angle_graph_video(
            kinematics_df,
            output_paths[group_name],
            columns,
            fps,
            titles[group_name],
            window_seconds,
        )
        print(f"{titles[group_name]} video saved to {output_paths[group_name]}")

    return output_paths


def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description="Calculate clinical kinematics from pose data")
    parser.add_argument("input_csv", help="Path to the input CSV file containing pose data")
    parser.add_argument("--output", "-o", help="Path to the output CSV file (default: 'clinical_kinematics.csv')", 
                        default="clinical_kinematics.csv")
    parser.add_argument(
        "--graph-video",
        help=(
            "Base MP4 path for graph videos. Creates three files: left upper body, "
            "right upper body, and middle area angles."
        ),
    )
    parser.add_argument(
        "--fps",
        type=float,
        default=DEFAULT_GRAPH_FPS,
        help=f"Frames per second for graph videos (default: {DEFAULT_GRAPH_FPS:g})",
    )
    parser.add_argument(
        "--graph-window-seconds",
        type=float,
        default=DEFAULT_GRAPH_WINDOW_SECONDS,
        help=(
            "Visible time window for graph videos in seconds "
            f"(default: {DEFAULT_GRAPH_WINDOW_SECONDS:g})"
        ),
    )
    args = parser.parse_args()
    
    # Parse the input CSV file
    pose_df = parse_pose_csv(args.input_csv)
    if pose_df is None:
        return
    
    # Extract landmark coordinates
    frames_data = extract_landmark_coordinates(pose_df)
    
    # Calculate kinematics
    kinematics_df = calculate_kinematics(frames_data)
    
    # Save the kinematics data to a CSV file
    try:
        kinematics_df.to_csv(args.output, index=False)
        print(f"Clinical kinematics data saved to {args.output}")
    except Exception as e:
        print(f"Error saving kinematics data: {e}")

    if args.graph_video:
        create_grouped_graph_videos(
            kinematics_df,
            args.graph_video,
            args.fps,
            args.graph_window_seconds,
        )


if __name__ == "__main__":
    main()
