import pandas as pd
import numpy as np
import argparse
import os
from typing import List, Tuple, Dict, Union


FrameKey = Union[int, Tuple[int, int]]
TARGET_PERSON_ID = 1
UPPER_BODY_ANGLE_COLUMNS = [
    "left_shoulder_angle",
    "right_shoulder_angle",
    "left_elbow_angle",
    "right_elbow_angle",
    "trunk_flexion",
    "trunk_lateral_flexion",
    "neck_flexion",
    "neck_lateral_flexion",
]
ANGLE_VIDEO_GROUPS = {
    "left": [
        "left_shoulder_angle",
        "left_elbow_angle",
    ],
    "right": [
        "right_shoulder_angle",
        "right_elbow_angle",
    ],
    "middle": [
        "trunk_flexion",
        "trunk_lateral_flexion",
        "neck_flexion",
        "neck_lateral_flexion",
    ],
}


def project_to_frontal(point: np.ndarray) -> np.ndarray:
    """Return the x/y coordinates used for frontal-plane calculations."""
    return np.array(point, dtype=float)[:2]


def calculate_angle(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> float:
    """
    Calculate the angle between three points in the frontal plane.
    The angle is calculated at point b.
    """
    # Convert to frontal-plane x/y coordinates.
    a = project_to_frontal(a)
    b = project_to_frontal(b)
    c = project_to_frontal(c)
    
    # Calculate vectors
    ba = a - b
    bc = c - b
    
    # Calculate cosine of angle using dot product
    denominator = np.linalg.norm(ba) * np.linalg.norm(bc)
    if denominator == 0 or np.isnan(denominator):
        return np.nan

    cosine_angle = np.dot(ba, bc) / denominator
    angle = np.arccos(np.clip(cosine_angle, -1.0, 1.0))
    
    # Convert to degrees
    angle = np.degrees(angle)
    
    return angle


def parse_pose_csv(csv_file: str) -> pd.DataFrame:
    """
    Parse the CSV file generated by the pose estimation script.
    Returns a DataFrame with all landmark coordinates.
    """
    # Read the CSV file
    df = pd.DataFrame()
    try:
        df = pd.read_csv(csv_file)
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return None

    if "person_id" in df.columns:
        original_rows = len(df)
        person_ids = pd.to_numeric(df["person_id"], errors="coerce")
        df = df[person_ids == TARGET_PERSON_ID].copy()
        print(
            f"Imported {len(df)} rows for person ID {TARGET_PERSON_ID} "
            f"from {original_rows} total rows."
        )
    
    return df


def extract_landmark_coordinates(df: pd.DataFrame) -> Dict[FrameKey, List[Tuple[float, float, float]]]:
    """
    Extract coordinates for each landmark from all frames.
    Returns a dictionary mapping frame_index or (frame, person_id) -> list of landmark coordinates.
    """
    frames_data = {}
    
    for frame_idx, row in df.iterrows():
        landmarks = []
        
        # For each of the 33 landmarks
        for i in range(33):
            x = row[f"landmark_{i}_x"]
            y = row[f"landmark_{i}_y"]
            z = row[f"landmark_{i}_z"]
            landmarks.append((x, y, z))
        
        if "frame" in df.columns and "person_id" in df.columns:
            key = (int(row["frame"]), int(row["person_id"]))
        else:
            key = frame_idx

        frames_data[key] = landmarks
    
    return frames_data


def calculate_kinematics(frames_data: Dict[FrameKey, List[Tuple[float, float, float]]]) -> pd.DataFrame:
    """
    Calculate clinically relevant kinematics from the landmark data.
    Returns a DataFrame with all calculated kinematics.
    """
    # Define the landmark indices for various joints
    # MediaPipe pose landmarks reference: https://mediapipe.dev/images/mobile/pose_tracking_full_body_landmarks.png
    landmarks = {
        # Left side
        "left_shoulder": 11,
        "left_elbow": 13,
        "left_wrist": 15,
        "left_hip": 23,
        "left_knee": 25,
        "left_ankle": 27,
        # Right side
        "right_shoulder": 12,
        "right_elbow": 14,
        "right_wrist": 16,
        "right_hip": 24,
        "right_knee": 26,
        "right_ankle": 28,
        # Central points
        "nose": 0,
        "neck": 33,  # Not directly in MediaPipe, we'll calculate it
        "left_ear": 7,
        "right_ear": 8,
    }
    
    # Initialize a dictionary to store the kinematics data
    kinematics_data = {
        # Joint angles
        "left_knee_angle": [],
        "right_knee_angle": [],
        "left_hip_angle": [],
        "right_hip_angle": [],
        "left_ankle_angle": [],
        "right_ankle_angle": [],
        "left_shoulder_angle": [],
        "right_shoulder_angle": [],
        "left_elbow_angle": [],
        "right_elbow_angle": [],
        # Trunk angles
        "trunk_flexion": [],
        "trunk_lateral_flexion": [],
        # Neck angles
        "neck_flexion": [],
        "neck_lateral_flexion": [],
        # Symmetry metrics
        "knee_angle_symmetry": [],
        "hip_angle_symmetry": [],
        "shoulder_angle_symmetry": []
    }
    
    # Process each frame
    for frame_idx, landmarks_list in frames_data.items():
        # Create a function to get coordinates for a landmark
        def get_landmark(idx):
            if idx == 33:  # Calculate neck position as midpoint between shoulders
                left_shoulder = np.array(landmarks_list[landmarks["left_shoulder"]])
                right_shoulder = np.array(landmarks_list[landmarks["right_shoulder"]])
                return (left_shoulder + right_shoulder) / 2
            else:
                return np.array(landmarks_list[idx])
        
        # Calculate joint angles
        
        # Knee angles (extension/flexion)
        left_knee_angle = calculate_angle(
            get_landmark(landmarks["left_hip"]), 
            get_landmark(landmarks["left_knee"]), 
            get_landmark(landmarks["left_ankle"])
        )
        right_knee_angle = calculate_angle(
            get_landmark(landmarks["right_hip"]), 
            get_landmark(landmarks["right_knee"]), 
            get_landmark(landmarks["right_ankle"])
        )
        
        # Hip angles (extension/flexion)
        # Use torso as reference (approximate with a vertical line from hip)
        left_hip_vertical = get_landmark(landmarks["left_hip"]) + np.array([0, -1, 0])
        right_hip_vertical = get_landmark(landmarks["right_hip"]) + np.array([0, -1, 0])
        
        left_hip_angle = calculate_angle(
            left_hip_vertical, 
            get_landmark(landmarks["left_hip"]), 
            get_landmark(landmarks["left_knee"])
        )
        right_hip_angle = calculate_angle(
            right_hip_vertical, 
            get_landmark(landmarks["right_hip"]), 
            get_landmark(landmarks["right_knee"])
        )
        
        # Ankle angles (dorsiflexion/plantarflexion)
        # Approximate with a horizontal line from ankle
        left_ankle_horizontal = get_landmark(landmarks["left_ankle"]) + np.array([1, 0, 0])
        right_ankle_horizontal = get_landmark(landmarks["right_ankle"]) + np.array([1, 0, 0])
        
        left_ankle_angle = calculate_angle(
            get_landmark(landmarks["left_knee"]),
            get_landmark(landmarks["left_ankle"]),
            left_ankle_horizontal
        )
        right_ankle_angle = calculate_angle(
            get_landmark(landmarks["right_knee"]),
            get_landmark(landmarks["right_ankle"]),
            right_ankle_horizontal
        )
        
        # Shoulder angles (flexion/extension)
        left_shoulder_vertical = get_landmark(landmarks["left_shoulder"]) + np.array([0, -1, 0])
        right_shoulder_vertical = get_landmark(landmarks["right_shoulder"]) + np.array([0, -1, 0])
        
        left_shoulder_angle = calculate_angle(
            left_shoulder_vertical,
            get_landmark(landmarks["left_shoulder"]),
            get_landmark(landmarks["left_elbow"])
        )
        right_shoulder_angle = calculate_angle(
            right_shoulder_vertical,
            get_landmark(landmarks["right_shoulder"]),
            get_landmark(landmarks["right_elbow"])
        )
        
        # Elbow angles (extension/flexion)
        left_elbow_angle = calculate_angle(
            get_landmark(landmarks["left_shoulder"]),
            get_landmark(landmarks["left_elbow"]),
            get_landmark(landmarks["left_wrist"])
        )
        right_elbow_angle = calculate_angle(
            get_landmark(landmarks["right_shoulder"]),
            get_landmark(landmarks["right_elbow"]),
            get_landmark(landmarks["right_wrist"])
        )
        
        # Trunk flexion (forward/backward lean)
        left_hip = get_landmark(landmarks["left_hip"])
        right_hip = get_landmark(landmarks["right_hip"])
        hip_center = (left_hip + right_hip) / 2
        
        left_shoulder = get_landmark(landmarks["left_shoulder"])
        right_shoulder = get_landmark(landmarks["right_shoulder"])
        shoulder_center = (left_shoulder + right_shoulder) / 2
        
        # Create a vertical line from hip center
        hip_vertical = hip_center + np.array([0, -1, 0])
        
        trunk_flexion = calculate_angle(
            hip_vertical,
            hip_center,
            shoulder_center
        )
        
        # Trunk lateral flexion (side bend) in the frontal plane
        hip_line = project_to_frontal(right_hip) - project_to_frontal(left_hip)
        hip_up = np.array([-hip_line[1], hip_line[0]])
        hip_up_norm = np.linalg.norm(hip_up)
        hip_to_shoulder_frontal = project_to_frontal(shoulder_center) - project_to_frontal(hip_center)
        hip_to_shoulder_norm = np.linalg.norm(hip_to_shoulder_frontal)

        if hip_up_norm == 0 or hip_to_shoulder_norm == 0:
            trunk_lateral_flexion = np.nan
        else:
            hip_up = hip_up / hip_up_norm
            trunk_lateral_flexion = np.degrees(np.arccos(
                np.clip(np.dot(hip_up, hip_to_shoulder_frontal) / hip_to_shoulder_norm, -1.0, 1.0)
            ))
        
        # Neck angles
        neck = get_landmark(landmarks["neck"])
        nose = get_landmark(landmarks["nose"])
        
        # Neck flexion
        neck_vertical = neck + np.array([0, -1, 0])
        neck_flexion = calculate_angle(
            neck_vertical,
            neck,
            nose
        )
        
        # Neck lateral flexion
        left_ear = get_landmark(landmarks["left_ear"])
        right_ear = get_landmark(landmarks["right_ear"])
        ear_center = (left_ear + right_ear) / 2
        
        # Create a vector from neck to ear center
        neck_to_ear = ear_center - neck
        
        # Calculate the angle between vertical and neck_to_ear in the frontal plane
        neck_to_ear_frontal = project_to_frontal(neck_to_ear)
        neck_to_ear_norm = np.linalg.norm(neck_to_ear_frontal)
        if neck_to_ear_norm == 0:
            neck_lateral_flexion = np.nan
        else:
            neck_lateral_flexion = np.degrees(np.arccos(
                np.clip(np.dot(np.array([0, -1]), neck_to_ear_frontal) / neck_to_ear_norm, -1.0, 1.0)
            ))
        
        # Calculate symmetry metrics (absolute difference between left and right)
        knee_angle_symmetry = abs(left_knee_angle - right_knee_angle)
        hip_angle_symmetry = abs(left_hip_angle - right_hip_angle)
        shoulder_angle_symmetry = abs(left_shoulder_angle - right_shoulder_angle)
        
        # Store the calculated kinematics
        kinematics_data["left_knee_angle"].append(left_knee_angle)
        kinematics_data["right_knee_angle"].append(right_knee_angle)
        kinematics_data["left_hip_angle"].append(left_hip_angle)
        kinematics_data["right_hip_angle"].append(right_hip_angle)
        kinematics_data["left_ankle_angle"].append(left_ankle_angle)
        kinematics_data["right_ankle_angle"].append(right_ankle_angle)
        kinematics_data["left_shoulder_angle"].append(left_shoulder_angle)
        kinematics_data["right_shoulder_angle"].append(right_shoulder_angle)
        kinematics_data["left_elbow_angle"].append(left_elbow_angle)
        kinematics_data["right_elbow_angle"].append(right_elbow_angle)
        kinematics_data["trunk_flexion"].append(trunk_flexion)
        kinematics_data["trunk_lateral_flexion"].append(trunk_lateral_flexion)
        kinematics_data["neck_flexion"].append(neck_flexion)
        kinematics_data["neck_lateral_flexion"].append(neck_lateral_flexion)
        kinematics_data["knee_angle_symmetry"].append(knee_angle_symmetry)
        kinematics_data["hip_angle_symmetry"].append(hip_angle_symmetry)
        kinematics_data["shoulder_angle_symmetry"].append(shoulder_angle_symmetry)
    
    # Create a DataFrame from the kinematics data
    kinematics_df = pd.DataFrame(kinematics_data)
    
    keys = list(frames_data.keys())
    if keys and isinstance(keys[0], tuple):
        kinematics_df.insert(0, "person_id", [key[1] for key in keys])
        kinematics_df.insert(0, "frame", [key[0] for key in keys])
    else:
        kinematics_df.insert(0, "frame", keys)
    
    return kinematics_df


def add_anatomical_validity(
    kinematics_df: pd.DataFrame,
    pose_df: pd.DataFrame,
) -> pd.DataFrame:
    """Copy the source pose validity flag onto the matching kinematics rows."""
    if "is_anatomically_valid" not in pose_df.columns:
        return kinematics_df

    result = kinematics_df.copy()
    if "frame" in pose_df.columns and "person_id" in pose_df.columns:
        validity = (
            pose_df.drop_duplicates(["frame", "person_id"], keep="last")
            .set_index(["frame", "person_id"])["is_anatomically_valid"]
        )
        row_keys = pd.MultiIndex.from_frame(result[["frame", "person_id"]])
        values = validity.reindex(row_keys).to_numpy()
    elif "frame" in pose_df.columns:
        validity = (
            pose_df.drop_duplicates("frame", keep="last")
            .set_index("frame")["is_anatomically_valid"]
        )
        values = result["frame"].map(validity).to_numpy()
    else:
        values = pose_df["is_anatomically_valid"].reindex(result["frame"]).to_numpy()

    insert_at = result.columns.get_loc("person_id") + 1 if "person_id" in result.columns else 1
    result.insert(insert_at, "is_anatomically_valid", values)
    return result


def create_angle_graph_video(
    kinematics_df: pd.DataFrame,
    output_video: str,
    angle_columns: List[str],
    fps: float,
    window_seconds: float,
    title: str,
) -> None:
    """
    Create an MP4 where angle traces scroll in real time.
    """
    import cv2
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if "frame" not in kinematics_df.columns:
        print("Error: Cannot create graph video because the kinematics data has no frame column.")
        return

    if fps <= 0:
        print("Error: FPS must be greater than 0 to create a graph video.")
        return

    if window_seconds <= 0:
        print("Error: Graph window seconds must be greater than 0.")
        return

    df = kinematics_df.copy()
    df["time"] = pd.to_numeric(df["frame"], errors="coerce") / fps
    df = df.sort_values("time").reset_index(drop=True)

    valid_angle_columns = [
        column for column in angle_columns if column in df.columns
    ]
    if not valid_angle_columns:
        print(
            "Error: None of the requested angle columns exist in the kinematics data. "
            f"Available columns: {', '.join(df.columns)}"
        )
        return

    df[valid_angle_columns] = df[valid_angle_columns].apply(
        pd.to_numeric,
        errors="coerce",
    )
    df = df.dropna(subset=["time"])
    if df.empty:
        print("Error: No valid frame/time data available for graph video.")
        return

    width, height = 1280, 720
    output_dir = os.path.dirname(output_video)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(output_video, fourcc, fps, (width, height))
    if not writer.isOpened():
        print(f"Error: Could not create graph video: {output_video}")
        return

    x_values = df["time"].to_numpy(dtype=float)
    y_values_by_column = {
        column: df[column].to_numpy(dtype=float)
        for column in valid_angle_columns
    }

    finite_values = np.concatenate(
        [
            values[np.isfinite(values)]
            for values in y_values_by_column.values()
            if np.isfinite(values).any()
        ]
    )
    if finite_values.size == 0:
        print("Error: No valid angle values available for graph video.")
        writer.release()
        return

    y_padding = 10
    y_min = float(np.nanmin(finite_values)) - y_padding
    y_max = float(np.nanmax(finite_values)) + y_padding
    if y_min == y_max:
        y_min -= y_padding
        y_max += y_padding

    x_min = float(np.nanmin(x_values))
    x_max = float(np.nanmax(x_values))
    if x_min == x_max:
        x_max = x_min + 1 / fps

    fig, ax = plt.subplots(figsize=(12.8, 7.2), dpi=100)
    lines = {}
    markers = {}
    for column in valid_angle_columns:
        (line,) = ax.plot([], [], label=column.replace("_", " "), linewidth=2)
        (marker,) = ax.plot([], [], marker="o", linestyle="None", markersize=6)
        lines[column] = line
        markers[column] = marker

    ax.set_title(title)
    ax.set_xlabel("Time (seconds)")
    ax.set_ylabel("Angle (degrees)")
    ax.set_ylim(y_min, y_max)
    ax.grid(True, alpha=0.35)
    ax.legend(loc="upper right", fontsize=8)
    fig.tight_layout()

    for frame_index in range(len(df)):
        current_time = x_values[frame_index]
        window_start = max(x_min, current_time - window_seconds)
        window_end = window_start + window_seconds
        if window_end > x_max:
            window_end = x_max
            window_start = max(x_min, window_end - window_seconds)

        window_mask = (
            (x_values >= window_start)
            & (x_values <= current_time)
        )

        for column in valid_angle_columns:
            y_values = y_values_by_column[column]
            lines[column].set_data(x_values[window_mask], y_values[window_mask])

            current_value = y_values[frame_index]
            if np.isfinite(current_value):
                markers[column].set_data([current_time], [current_value])
            else:
                markers[column].set_data([], [])

        ax.set_xlim(window_start, window_end)
        ax.set_title(f"{title} - {current_time:.2f}s")

        fig.canvas.draw()
        frame_rgba = np.asarray(fig.canvas.buffer_rgba())
        frame_rgb = frame_rgba[:, :, :3]
        frame_bgr = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR)
        writer.write(frame_bgr)

        if (frame_index + 1) % 100 == 0:
            print(f"Rendered {output_video} frame {frame_index + 1}/{len(df)}")

    plt.close(fig)
    writer.release()
    print(f"Angle graph video saved to {output_video}")


def grouped_graph_video_path(output_video: str, group_name: str) -> str:
    base, extension = os.path.splitext(output_video)
    if not extension:
        extension = ".mp4"
    return f"{base}_{group_name}{extension}"


def create_upper_body_angle_graph_videos(
    kinematics_df: pd.DataFrame,
    output_video: str,
    fps: float,
    window_seconds: float,
) -> None:
    for group_name, angle_columns in ANGLE_VIDEO_GROUPS.items():
        group_output = grouped_graph_video_path(output_video, group_name)
        create_angle_graph_video(
            kinematics_df,
            group_output,
            angle_columns,
            fps,
            window_seconds,
            f"{group_name.title()} Upper Body Angles",
        )


def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description="Calculate clinical kinematics from pose data")
    parser.add_argument("input_csv", help="Path to the input CSV file containing pose data")
    parser.add_argument("--output", "-o", help="Path to the output CSV file (default: 'clinical_kinematics.csv')", 
                        default="clinical_kinematics.csv")
    parser.add_argument(
        "--fps",
        type=float,
        default=30.0,
        help="Video FPS used to convert frame numbers into seconds for graph output.",
    )
    parser.add_argument(
        "--graph-video",
        help="Optional base MP4 output path for animated upper-body angle graphs. Creates _left, _right, and _middle videos.",
    )
    parser.add_argument(
        "--graph-window-seconds",
        type=float,
        default=30.0,
        help="Number of seconds shown in the scrolling graph window.",
    )
    args = parser.parse_args()
    
    # Parse the input CSV file
    pose_df = parse_pose_csv(args.input_csv)
    if pose_df is None:
        return
    
    # Extract landmark coordinates
    frames_data = extract_landmark_coordinates(pose_df)
    
    # Calculate kinematics
    kinematics_df = calculate_kinematics(frames_data)
    kinematics_df = add_anatomical_validity(kinematics_df, pose_df)
    kinematics_df["time"] = kinematics_df["frame"] / args.fps
    
    # Save the kinematics data to a CSV file
    try:
        kinematics_df.to_csv(args.output, index=False)
        print(f"Clinical kinematics data saved to {args.output}")
    except Exception as e:
        print(f"Error saving kinematics data: {e}")

    if args.graph_video:
        create_upper_body_angle_graph_videos(
            kinematics_df,
            args.graph_video,
            args.fps,
            args.graph_window_seconds,
        )


if __name__ == "__main__":
    main()
